### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [jamesfoster85/firehose-install#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jamesfoster85** [comment]
I saw exactly what you meant when I opened it up on my Galaxy S5, looked alright in landscape but portrait was bad... (Test early and often!).  Added a viewport meta tag that at least fixed it on my test environment.

**Comment by kenmazaika** [comment]
Thumbs up. :+1:

Solid! :)
